sudo: required
dist: trusty

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  pip: true
  directories:
    - $HOME/.pip-cache/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-cmake-3.x
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - git
      # Optional dependencies
      - libtbb-dev
branches:
  only:
    - master
env:
  global:
    - USE_TBB=ON
    - BUILD_TESTS=ON
    - BUILD_EXAMPLES=ON
    - COVERALLS=ON
 
  matrix:
    - USE_SSE=OFF USE_AVX=OFF
    - USE_SSE=ON  USE_AVX=ON

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default 
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
       export CC="gcc-4.8";
       export CXX="g++-4.8";
    fi
  - gcc --version
  - g++ --version

install:
  - bash -x .travis/install.sh
  - pip install --user cpp-coveralls

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        cmake -DUSE_TBB=$USE_TBB
              -DUSE_SSE=$USE_SSE
              -DUSE_AVX=$USE_AVX
              -DBUILD_TESTS=$BUILD_TESTS
              -DCOVERALLS=$COVERALLS
              -DBUILD_EXAMPLES=$BUILD_EXAMPLES .;
      else
        cmake -DUSE_TBB=$USE_TBB
              -DUSE_SSE=$USE_SSE
              -DUSE_AVX=$USE_AVX
              -DBUILD_TESTS=$BUILD_TESTS
              -DBUILD_EXAMPLES=$BUILD_EXAMPLES .;
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then
      cmake -DUSE_TBB=$USE_TBB
            -DUSE_AVX=OFF
            -DBUILD_TESTS=$BUILD_TESTS .;
    fi
  
script: make -j2 && ./test/tiny_dnn_test

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
    coveralls
      --exclude test
      --exclude examples
      --exclude cereal
      --exclude third_party
      --exclude build/CMakeFiles
      --exclude /usr/include
      --gcov-options '\-lp'
    fi
