sudo: required
dist: trusty

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  pip: true
  directories:
    - $HOME/.pip-cache/
    - $HOME/PeachPy
    - $HOME/NNPACK

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-cmake-3.x
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - git
      # Optional dependencies
      - libtbb-dev
branches:
  only:
    - master
    - feat/generic-computational-graph
env:
  global:
    - BUILD_TESTS=ON
    - BUILD_EXAMPLES=ON
 
  matrix:
    - USE_SSE=OFF USE_AVX=OFF
    - USE_SSE=ON  USE_AVX=ON

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default 
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
       export CC="gcc-4.8";
       export CXX="g++-4.8";
    fi
  - gcc --version
  - g++ --version

install:
  - bash -x .travis/install.sh
  - pip install --user cpp-coveralls

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cmake -DUSE_SSE=$USE_SSE
            -DUSE_AVX=$USE_AVX
            -DBUILD_TESTS=$BUILD_TESTS
            -DCOVERALLS=ON
            -DBUILD_EXAMPLES=$BUILD_EXAMPLES .;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then
      cmake -DUSE_TBB=ON 
            -DUSE_AVX=OFF
            -DBUILD_TESTS=$BUILD_TESTS .;
    fi
  
script: make -j2 && ./test/tiny_dnn_test

after_success:
  - coveralls --exclude build/CMakeFiles --exclude /usr/include --gcov-options '\-lp'
